version: "3.9"

services:

  # [プロジェクトごとに設定]webアプリケーションのコンテナ
  project_1:
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile
      target: php81
    volumes:
      - ./projects/project_1/:/app/project_1
    working_dir: /app/project_1

  project_2:
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile
      target: php73
    volumes:
      - ./projects/project_2/:/app/project_2
    working_dir: /app/project_2

  # [プロジェクト共通]webサーバーのコンテナ(プロジェクトごとにports,depends_on,volumesを設定)
  web:
    build:
      context: .
      dockerfile: ./infra/web/Dockerfile
    ports:
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - project_1
      - project_2
    volumes:
      - ./projects/project_1/:/app/project_1
      - ./projects/project_2/:/app/project_2

  # [プロジェクト共通]dbサーバーのコンテナ
  db:
    build:
      context: .
      dockerfile: ./infra/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: